#!/usr/bin/env bash

# Display listening ports with PID and program name

# Run netstat command to get listening sockets
netstat -tlnp | awk 'NR>2 {
    split($NF,a,"/");
    printf "Port: %s\tPID: %s\tProgram: ", $4, a[1];
    for(i=7;i<=NF;i++){ printf "%s ", $i };
    printf "\n";
}'
